name: account_manager
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0
  
dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  sqflite: ^2.4.1
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0
  
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Kablammo
      fonts:
        - asset: assets/fonts/Kablammo-Regular.ttf
    - family: RubikBeastly
      fonts:
        - asset: assets/fonts/RubikBeastly-Regular.ttf
    - family: FasterOne
      fonts:
        - asset: assets/fonts/FasterOne-Regular.ttf
    - family: AllertaStencil
      fonts:
        - asset: assets/fonts/AllertaStencil-Regular.ttf